### ISSUE TITLE
please license this

### ISSUE THREAD

**Issue by ex-nerd** [zewelor/linak_bt_desk#3]
This seems to be in use by https://github.com/anetczuk/linak_bt_desk (forked, with updates/fixes) but the repo itself is not licensed so it's hard to know what is/isn't allowed.

See companion ticket here: https://github.com/anetczuk/LinakDeskApp/issues/13

**Comment by zewelor** [comment]
Hi

Thanks for noticing it. Is it ok now ? https://github.com/zewelor/linak_bt_desk/blob/master/LICENSE

**Comment by ex-nerd** [comment]
Cool, thanks!  Hopefully the forked/updated copy will do the same.
